# Generated by Django 5.1.3 on 2024-11-21 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        ("supportAgent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("closing_time", models.DateTimeField(blank=True, null=True)),
                (
                    "service",
                    models.CharField(
                        choices=[("0", "Telegram"), ("1", "WhatsApp")], max_length=2
                    ),
                ),
                (
                    "contact_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_chats",
                        to="contact.contact",
                    ),
                ),
                (
                    "support_agent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_chats",
                        to="supportAgent.supportagent",
                    ),
                ),
            ],
        ),
    ]
