# Generated by Django 5.1.3 on 2024-11-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_message_sender_content_type_message_sender_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="updated_at",
        ),
    ]
