[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["Manuele Lamenha <manuele.lamenha.mauricio@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
