# Generated by Django 5.1.3 on 2024-11-21 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
